name: Configure XCode
description: Configure the workflow to use the latest XCode version

runs:
  using: composite
  steps:
    # Get xcode version from .xcode-version
    - name: Determine Xcode Version
      id: xcode-version
      shell: bash
      run: |
        echo "version=$(cat .xcode-version)" >> $GITHUB_OUTPUT
    # Make sure we use the correct xcode version
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: ${{ steps.xcode-version.outputs.version }}
