# The CI workflow to build the library (triggers manually or by pushing code to `main` or `develop`)
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop", "klogi/*" ]
  pull-request:
    branches: [ "main", "develop", "klogi/*" ]

jobs:
  build:
    name: Compile Library
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure Xcode
      uses: ./.github/actions/configure-xcode

    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
